# Generated by Django 5.2.5 on 2025-11-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='synergist_muscle',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='target_muscle',
        ),
    ]
