# Generated by Django 5.2.7 on 2025-12-13 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howto', '0004_alter_bookmark_exercise_alter_bookmark_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmark',
            new_name='ExerciseFavorite',
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['main_muscle', 'exercise_name']},
        ),
        migrations.DeleteModel(
            name='ExerciseBookmark',
        ),
    ]
