# Generated by Django 5.2.5 on 2025-10-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='date_update',
        ),
        migrations.AddField(
            model_name='thread',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
