# Generated by Django 5.2.7 on 2025-10-14 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_reply_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='community.reply'),
        ),
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
