# Generated by Django 5.2.7 on 2025-10-22 17:24

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(max_length=40, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('favorite_workouts', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bench-press', 'Bench Press (Dada)'), ('push-up', 'Push-up (Dada / Lengan)'), ('pull-up', 'Pull-up (Punggung / Lengan)'), ('deadlift', 'Deadlift (Punggung / Kaki)'), ('squat', 'Squat'), ('lunges', 'Lunges'), ('shoulder-press', 'Shoulder Press'), ('bicep-curl', 'Bicep Curl'), ('tricep-dips', 'Tricep Dips'), ('running', 'Lari (Running)'), ('treadmill', 'Treadmill'), ('cycling', 'Bersepeda (Cycling)'), ('rowing', 'Rowing'), ('jump-rope', 'Lompat Tali (Jump Rope)'), ('plank', 'Plank'), ('mountain-climber', 'Mountain Climber'), ('box-jump', 'Box Jump'), ('kettlebell-swing', 'Kettlebell Swing'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('stretching', 'Peregangan (Stretching)'), ('zumba', 'Zumba / Aerobik')], max_length=209)),
            ],
        ),
    ]
