# Generated by Django 5.2.8 on 2025-11-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howto', '0002_remove_exercise_synergist_muscle_and_more'),
        ('user_profile', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_workouts',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_workouts',
            field=models.ManyToManyField(blank=True, to='howto.exercise'),
        ),
    ]
