# Generated by Django 5.2.7 on 2025-10-23 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('howto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(help_text='Number of sets to perform.')),
                ('reps', models.PositiveIntegerField(help_text='Number of repetitions per set.')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time this plan was created.')),
                ('exercise', models.ForeignKey(help_text='The exercise chosen for this plan.', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='howto.exercise')),
                ('user', models.ForeignKey(help_text='The user who created this workout plan.', on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
