# Generated by Django 5.2.7 on 2025-10-24 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['plan_date', 'id']},
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='date_created',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='plan_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
