# Generated by Django 5.2.7 on 2025-10-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_workoutplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['-plan_date', 'is_completed', 'id']},
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Waktu ketika latihan ditandai selesai.', null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='description',
            field=models.TextField(blank=True, help_text='Catatan atau deskripsi setelah latihan diselesaikan.', null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Apakah rencana latihan ini sudah diselesaikan?'),
        ),
    ]
